server:
  port: 8083

spring:
  application:
    name: funding-service

  datasource:
    url: jdbc:postgresql://localhost:5432/investments
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.cinefund.fundingservice: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
